"use client";

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from '@/components/Provider'
import { ReactElement } from 'react'
import { Provider as ReduxProvider } from 'react-redux'
import { store } from './redux/store'
import LeftMenu from '@/components/LeftMenu';
import RightMenu from '@/components/RightMenu';
import Modal from '@/components/Modal';
import Toast from '@/components/Toast';

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Home / Y',
//   description: 'Generated by create next app',
// }

type ChildrenType = {
  children: ReactElement
}

export default function RootLayout({ children }: ChildrenType) {
  return (
    <html lang="en">
        <Provider>
          <ReduxProvider store={store}>
            <body className="flex justify-between mx-auto relative">
              <LeftMenu />
                {children}
              <RightMenu />
              {/* Global Overlay */}
              <Modal />
              <Toast />
            </body>
          </ReduxProvider>
        </Provider>
    </html>
  )
}
